spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bmg_poc
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

api:
  security:
    jwt:
      secret-key: "NDQ1MzQ1MzQ1NDM1MzQ1MzQ1MzQ1NDM1MzQ1MzQ1MzQ1NDM1MzQ1MzQ1MzQ1NDM1MzQ="
      expiration: 60000
    refresh-token:
      expiration: 43200000